# Generated by Django 5.1.2 on 2025-02-03 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='live_demo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='video_demo',
            field=models.FileField(blank=True, null=True, upload_to='project_videos/'),
        ),
    ]
